
# This is a basic workflow to help you get started with Actions

name: bayes:0.0

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string : 
#    weekly #m h d/m m d/w 
#    - cron:  '30 1 * * 1'
#    every month 3.rd day
    - cron:  '41 8 3 * *' 
   
jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: credocker/crecoding:2024.0
      volumes:
        - ${{ github.workspace }}:/cre/python
    steps:
      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
#        with:
#          ref: main
      - name: cd /cre/python/
        run: (cd /cre/python/)
      - name: Install HanTa textblob_de
        run: (pip3 install HanTa textblob==0.15.3 textblob_de==0.4.3 scikit-learn) 
      - name: Run bayes
        run: (python3 bayes.py)
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
        with:
#          pull: '--rebase --autostash ...'
          add: 'img/words_bayes_*.png  csv/words_bayes_*.csv'
          tag_push: '--force'
