
# This is a basic workflow to help you get started with Actions

name: heatmap:0.0

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string : 
#    weekly #m h d/m m d/w 
#    - cron:  '30 1 * * 1'
#    daily #m h d/m m d/w 
    - cron:  '55 1 * * *'
   
jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: credocker/crepython:2024.0
      volumes:
        - ${{ github.workspace }}:/cre/python
    steps:
      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
#        with:
#          ref: main
      - name: cd /cre/python/
        run: (cd /cre/python/)
      - name: Install shapely cartopy
        run: (pip3 install shapely cartopy --no-binary shapely --no-binary cartopy)
      - name: Install folium pillow
        run: (pip3 install folium pillow)
      - name: Run diagrams
        run: (python3 heatmap.py)
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
        with:
#          pull: '--rebase --autostash ...'
          add: 'img/heatmap.png'
          tag_push: '--force'
